---
- name: Install wget utility
  yum:
    name: wget
    state: present
    
- name: Install telnet utility
  yum:
    name: telnet
    state: present
    
- name: Install firewalld utility
  yum:
    name: firewalld
    state: present

- name: Install java jdk
  yum:
    pkg: /tmp/jdk-8u191-linux-x64.rpm
    state: present
    
- name: Disabling SELinux
  command: "sed -i 's/=enforcing/=disabled/g' /etc/selinux/config"
  
- name: Make firwalld as bootable Service
  systemd:
    name: firewalld
    enabled: true

- name: Start firewalld service
  systemd:
    name: firewalld
    state: started
    
- name: Opening required ports
  command: "firewall-cmd --zone=public --add-port=8010-9000/tcp --permanent"
  
- name: Opening required ports
  command: "firewall-cmd --reload"

- name: Downloading Maven
  command: "wget http://www-us.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz -O /tmp/apache-maven-3.5.4-bin.tar.gz"

- name: Install Maven  and setup
  command: "cd /tmp/ && tar -xf /tmp/apache-maven-3.5.4-bin.tar.gz && mv /tmp/apache-maven-3.5.4/ /usr/local/src/apache-maven/ && mv /tmp/maven.sh /etc/profile.d/maven.sh && chmod +x /etc/profile.d/maven.sh"

- name: Install tomcat
  yum:
    name: tomcat
    state: present

- name: Configuring tomcat
  command: "mv -f /tmp/tomcat.conf /usr/share/tomcat/conf/"

- name: Install PostgreSQL database server
  yum: pkg={{item}} state=installed
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps
    - tomcat-docs-webapp
    - tomcat-javadoc

- name: Configuring tomcat
  command: "mv -f /tmp/tomcat-users.xml /usr/share/tomcat/conf/"

- name: Configuring tomcat
  command: "sed -i 's/8080/8010/g' /usr/share/tomcat/conf/server.xml"

- name: Make Tomcat as bootable Service
  systemd:
    name: tomcat
    enabled: true

- name: Start Tomcat service
  systemd:
    name: tomcat
    state: started
